---
- set_fact:
    src_registry: 'registry.access.redhat.com'
    image_tag: 'latest'

    images:
      - cloudforms46/cfme-openshift-postgresql
      - cloudforms46/cfme-openshift-memcached
      - cloudforms46/cfme-openshift-app-ui
      - cloudforms46/cfme-openshift-app
      - cloudforms46/cfme-openshift-embedded-ansible
      - cloudforms46/cfme-openshift-httpd
      - cloudforms46/cfme-httpd-configmap-generator
      - rhgs3/rhgs-server-rhel7
      - rhgs3/rhgs-volmanager-rhel7
      - rhgs3/rhgs-gluster-block-prov-rhel7
      - rhgs3/rhgs-s3-server-rhel7
      - openshift3/ose-service-catalog
      - openshift3/ose-ansible-service-broker
      - openshift3/mediawiki-apb
      - openshift3/postgresql-apb
      - rhel7/rsyslog
      - rhel7/etcd
